[package]
name = "mos6502-disassembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mos6502 = { path = "../mos6502"}
bus = { path = "../bus"}