name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C link-dead-code"

jobs:
  coverage:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/paulomigalmeida/manes-ci:latest
      options: --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v3
    - name: Run code coverage
      run:  cargo tarpaulin --workspace -v --exclude "manes" --out Xml --fail-under 90
#    - name: Upload to codecov.io
#      uses: codecov/codecov-action@v2
#      with:
#        fail_ci_if_error: true

