name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C link-dead-code"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y kcov
    - name: Filesystem prep
      run: cargo clean && mkdir output
    - name: Build
      run: cargo test --workspace --exclude "manes" --no-run --verbose
    - name: Coverage (Mos6502)
      run: |
            for i in `ls target/debug/deps/mos6502-*`; do
              if grep -qi elf $i ; then
                echo "found $i" 
                kcov \
                  --exclude-path=/usr/lib,/.cargo,/usr/include/,/MaNES/src/bus,/MaNES/src/mos6502-disassembler \
                  --verify output/ $i
              fi
            done
    - name: Coverage (Bus)
      run: |
            for i in `ls target/debug/deps/bus-*`; do
              if grep -qi elf $i ; then
                echo "found $i" 
                kcov \
                  --exclude-path=/usr/lib,/.cargo,/usr/include/,/MaNES/src/mos6502,/MaNES/src/mos6502-disassembler \
                  --verify output/ $i
              fi
            done
    
    - name: Coverage (Mos6502 Disassembler)
      run: |
            for i in `ls target/debug/deps/mos6502_disassembler-*`; do
              if grep -qi elf $i ; then
                echo "found $i" 
                kcov \
                  --exclude-path=/usr/lib,/.cargo,/usr/include/,/MaNES/src/mos6502,/MaNES/src/bus \
                  --verify output/ $i
              fi
            done
