name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C link-dead-code"

jobs:
  unittests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
            sudo apt-get install -y libssl-dev
            cargo install cargo-tarpaulin
    - name: Run code coverage
      run:  cargo tarpaulin --workspace -v --exclude "manes"

